spring:
  datasource:
    url: jdbc:postgresql://postgres-library:5432/library
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/library-api-realm

eureka:
  client:
    serviceUrl:
      defaultZone: http://library-server:8761/eureka/