spring:
  application:
    name: library-service
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

springdoc:
  api-docs:
    path: /api/library/v3/api-docs
  swagger-ui:
    path: /api/library/swagger-ui.html