version: '3.8'
services:
  postgres-books:
    build: postgres-books
    ports:
      - '5431:5431'
    environment:
      - POSTGRES_DB=books
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGDATA=/data/postgres-books
    volumes:
      - ./postgres-books-data:/data/postgres-books

  postgres-library:
    build: postgres-library
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGDATA=/data/postgres-library
    volumes:
      - ./postgres-library-data:/data/postgres-library

  postgres-keycloak:
    image: postgres:16
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    hostname: keycloak
    depends_on:
      - postgres-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-keycloak/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=1234
    ports:
      - '8090:8080'
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realms:/opt/keycloak/data/import/

  library-server:
    build: library-server
    ports:
      - '8761:8761'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - SERVER_PORT=8761

  book-service:
    build: book-service
    depends_on:
      - postgres-books
      - library-server
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-books:5431/books

  library-service:
    build: library-service
    depends_on:
      - postgres-library
      - library-server
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-library:5432/library

  library-gateway:
    build: library-gateway
    ports:
      - '8080:8080'
    depends_on:
      - book-service
      - library-service
      - keycloak
    environment:
      - SPRING_PROFILES_ACTIVE=docker