spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: 1234

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 0