spring:
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      default:
        timeoutDuration: 5s

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0

springdoc:
  api-docs:
    path: /api/books/v3/api-docs
  swagger-ui:
    path: /api/books/swagger-ui.html