spring:
  application:
    name: library-gateway
  cloud:
    gateway:
      routes:
      - id: book-service
        uri: lb://book-service
        predicates:
          - Path=/api/books/**
      - id: library-service
        uri: lb://library-service
        predicates:
          - Path=/api/library/**
      default-filters:
        - TokenRelay
        - SaveSession
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s
  session:
    redis:
      namespace: library:gateway
    timeout: 10m
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: library-gateway-client
            client-secret: GbLnqywXMan94yO6MmhqxjsuAAr4tmr9
            scope: openid, roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/library-api-realm

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080